### ISSUE TITLE
TSV or BED file?

### ISSUE THREAD

**Issue by visze** [kircherlab/negative_training_sampler#4]
I was wondering if you use a TSV or a BED file. Here the main questions are:

- Zero or One based
- End is inclusive or exclusive

From your example it looks like a BED file (zero based and end exclusive).

I think when working with genomic regions the best is to support the BED format. See here for a file description: https://genome.ucsc.edu/FAQ/FAQformat.html#format1

Do you support (b)zipped tsv/bed files?

**Comment by sroener** [comment]
> I was wondering if you use a TSV or a BED file.

As the initial calculation of the GC content is done by pybedtools, I use the file formats used by bedtools (in this case BED/GFF/VCF) as input.

> Do you support (b)zipped tsv/bed files?

Pybedtools supports gzipped versions of BED/GFF/VCF files and should recognize them automatically.

**Comment by visze** [comment]
thanks. Maybe you should change the documentation to bed and write about the bed files.

Can the regions ave different lengths?

**Comment by sroener** [comment]
>Can the regions ave different lengths?

Theoretically, yes. But I would discourage using regions of different lengths.

I assumed that all input regions are of the same length, so that they are easily usable as input for CNNs. Meaning that I don't change the lengths of regions and it could happen that regions of different lenghts are associated with each other based on their GC content. 

So far, I used [seqdataloader](https://github.com/kundajelab/seqdataloader) to generate the sliding windows over the genome.

**Comment by visze** [comment]
so also something missing in the documentation :-)
